x = (input('Digite algo: '))
print('O valor é:', x)
print('O tipo primitivo desse valor é: ', type(x))
print('Esse valor é alphanumerico?', x.isalnum())
print('Esse valor é numerico?', x.isnumeric())
print('Esse valor está com capslock?', x.isupper())
print('Esse valor é decimal?', x.isdecimal())